### ISSUE TITLE
correction module title 

### ISSUE THREAD

**Issue by HAMADOns** [MikeCodeur/typescript-expert#1]
corriger le titre de l'exo1

<img width="442" alt="image" src="https://github.com/MikeCodeur/typescript-expert/assets/47363693/dabfdc67-a441-4f60-9bca-a9f633e8af1a">

**Comment by MikeCodeur** [comment]
@HAMADOns Quel contexte ? 
- Ancien course-app ? / nouveau -course-app ?
- D'où vient le problème ? 
- Une piste ?
