### ISSUE TITLE
fix links feedback

### ISSUE THREAD

**Issue by HAMADOns** [MikeCodeur/typescript-expert#2]
@MikeCodeur  je vais corriger les liens feedback de ce module .

ce qui existe maintenat : 
<img width="209" alt="image" src="https://github.com/MikeCodeur/typescript-expert/assets/47363693/24385900-1096-4581-adcb-3ffaa7006990">

**Comment by MikeCodeur** [comment]
@HAMADOns est le problème ?

**Comment by HAMADOns** [comment]
@MikeCodeur le nom du module doit etre 5. Expert et la section aussi c autre chose, dans l'existant maintenant tout les formulaires ont le meme nom de module et section

**Comment by HAMADOns** [comment]
links corrigés sur les 2 branches 
https://github.com/MikeCodeur/typescript-expert/pull/3
